POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json
{
  name: "Nikolas",
  email: "burk@prisma.io"
}

###

POST http://localhost:3000/post HTTP/1.1
Content-Type: application/json
{
  title: "Hello World",
  authorEmail: "alice@prisma.io"
}

###

PUT http://localhost:3000/post HTTP/1.1
{
  title: "Hello World",
  authorEmail: "alice@prisma.io"
}